#!/bin/bash
#ICON=$HOME/Pictures/179237.png
TMPBG=/tmp/screen.png
scrot /tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -b --nofork -i $TMPBG
