#!/bin/bash
mkdir ~/mount
mkdir ~/mount/C
mkdir ~/mount/Apps
mkdir ~/mount/Archive
mkdir ~/mount/Dump
mkdir ~/mount/Extra
sudo mount /dev/sda2 ~/mount/C
sudo mount /dev/sdb1 ~/mount/Archive
sudo mount /dev/sdb2 ~/mount/Apps
sudo mount /dev/sdb3 ~/mount/Dump
sudo mount /dev/sdb4 ~/mount/Extra
